version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: coffee_machine_db
    restart: always
    environment:
      POSTGRES_USER: coffee_machine_admin
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: coffee_machine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  coffee_machine_app:
    build:
      context: .
    container_name: coffee_machine_app
    restart: always
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/coffee_machine_db
      DB_USERNAME: coffee_machine_admin
      DB_PASSWORD: Password123!
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ./mvnw spring-boot:run

volumes:
  postgres_data: